version: '3.8'
services:
  mongodb:
    image: mongo:4.2
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: secondTechChallengeDB
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongoadmin:secret@mongodb:27017/secondTechChallengeDB?authSource=admin
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    ports:
      - 8080:8080
      - 5005:5005
    depends_on:
      - mongodb

volumes:
  mongo-data:
