
spring:
  data:
    mongodb:
      uri: mongodb://mongoadmin:secret@localhost:27017/secondTechChallengeDB?authSource=admin
      database: secondTechChallengeDB
      username: mongoadmin
      password: secret