spring:
  data:
    mongodb:
      uri: mongodb://mongoadmin:secret@localhost:27017/secondTechChallengeDB
      host: localhost
      port: 27017
      database: secondTechChallengeDB
      username: mongoadmin
      password: secret
