package br.com.fiap.park_tech.model;

import br.com.fiap.park_tech.dto.ParkingSlotDTO;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;
import java.time.LocalDateTime;

@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
@Document(collection = "parking_slots")
public class ParkingSlot {
    @Id
    private String  id;
    private String slotName;
    private boolean available;
    private ParkingMeter parkingMeter;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private LocalDateTime deletedAt;

  public static ParkingSlot newParkingSlot(ParkingSlotDTO dto, ParkingMeter parkingMeter) {
    return  new ParkingSlot(
      null, // id will be generated by MongoDB
      dto.getSlotName(),
      true, // available
      parkingMeter,
      LocalDateTime.now(), // createdAt
      LocalDateTime.now(), // updatedAt
      null // deletedAt
    );
  }
}
