package br.com.fiap.park_tech.model;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;
import java.time.LocalDateTime;
import java.util.List;

@AllArgsConstructor
@Getter
@Setter
@Document(collection = "parking_meters")
public class ParkingMeter {
    @Id
    private String id;
    private String name;
    private List<ParkingSlot> parkingSlots;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private LocalDateTime deletedAt;

  public static ParkingMeter newParkingMeter(String name) {
    return new ParkingMeter(
      null, // id will be generated by MongoDB
      name,
      List.of(), // empty list of parking slots
      LocalDateTime.now(), // createdAt
      LocalDateTime.now(), // updatedAt
      null // deletedAt
    );
  }
}
