package br.com.fiap.park_tech.model;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;
import java.time.LocalDateTime;

@AllArgsConstructor
@Getter
@Setter
@Document(collection = "parking_sessions")
public class ParkingSession {
    @Id
    private String id;
    private Vehicle vehicle;
    private ParkingSlot parkingSlot;
    private VehiclePayment vehiclePayment;
    private LocalDateTime checkIn;
    private LocalDateTime checkOut;
    private Instant createdAt;
    private Instant updatedAt;
    private Instant deletedAt;

    public static ParkingSession newParkingSession(Vehicle vehicle, ParkingSlot parkingSlot, VehiclePayment vehiclePayment) {
        return new ParkingSession(
                null, // id will be generated by MongoDB
                vehicle,
                parkingSlot,
                vehiclePayment,
                LocalDateTime.now(), // checkIn
                null, // checkOut
                Instant.now(), // createdAt
                Instant.now(), // updatedAt
                null // deletedAt
        );
    }

}
