package br.com.fiap.park_tech.model;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;
import java.util.List;

@AllArgsConstructor
@Getter
@Setter
@Document(collection = "vehicles")
public class Vehicle {
    @Id
    private String id;
    private String licensePlate;
    private List<ParkingSession> parkingSessions;
    private Instant createdAt;
    private Instant updatedAt;
    private Instant deletedAt;

    public static Vehicle newVehicle(String licensePlate) {
        return new Vehicle(
                null, // id will be generated by MongoDB
                licensePlate,
                List.of(), // empty list of parking sessions
                Instant.now(), // createdAt
                Instant.now(), // updatedAt
                null // deletedAt
        );
    }

}
